___

<a href='https://www.udemy.com/user/joseportilla/'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Content Copyright by Pierian Data</em></center>

# Iterators and Generators Homework 

### Problem 1

Create a generator that generates the squares of numbers up to some number N.

In [1]:
def gensquares(N):

    for i in range(N):
        yield i**2

In [3]:
for x in gensquares(5):
    print(x)

0
1
4
9
16


### Problem 2

Create a generator that yields "n" random numbers between a low and high number (that are inputs). <br>Note: Use the random library. For example:

In [4]:
import random

random.randint(1,10)

3

In [5]:
def rand_num(low,high,n):

    for _ in range(n):
        yield random.randint(low,high)

In [6]:
for num in rand_num(1,10,12):
    print(num)

4
4
9
5
9
10
9
10
5
9
1
7


### Problem 3

Use the iter() function to convert the string below into an iterator:


In [7]:
s = 'hello'

#code here

### Problem 4
Explain a use case for a generator using a yield statement where you would not want to use a normal function with a return statement.<br><br><br><br><br><br>



In [8]:
import numpy as np

def batch_generator(X, y, batch_size):
    n_samples = len(X)
    for i in range(0, n_samples, batch_size):
        X_batch = X[i:i+batch_size]
        y_batch = y[i:i+batch_size]
        yield X_batch, y_batch  # produce one batch at a time

# Example data
X = np.arange(20).reshape(10, 2)
y = np.arange(10)

# Use generator
for X_batch, y_batch in batch_generator(X, y, batch_size=3):
    print("X_batch:\n", X_batch)
    print("y_batch:", y_batch)
    print("---")


X_batch:
 [[0 1]
 [2 3]
 [4 5]]
y_batch: [0 1 2]
---
X_batch:
 [[ 6  7]
 [ 8  9]
 [10 11]]
y_batch: [3 4 5]
---
X_batch:
 [[12 13]
 [14 15]
 [16 17]]
y_batch: [6 7 8]
---
X_batch:
 [[18 19]]
y_batch: [9]
---


### Extra Credit!
Can you explain what *gencomp* is in the code below? (Note: We never covered this in lecture! You will have to do some Googling/Stack Overflowing!)

In [9]:
my_list = [1,2,3,4,5]

gencomp = (item for item in my_list if item > 3)

for item in gencomp:
    print(item)

4
5


Hint: Google *generator comprehension*!

# Great Job!